### ISSUE TITLE
Asynchronous version

### ISSUE THREAD

**Issue by describe19** [sleepyfran/itunespy#12]
Hi would it be possible to make an async version with aiohttp? I would modify it myself but I'm fairly new to python so if it's something you're willing to do I'd be grateful. Otherwise if you could point me in the right direction that'd be good too.

**Comment by sleepyfran** [comment]
Hey! Unfortunately this is not something that I'm planning to do. I don't want any huge changes to the library unless they're necessary since the goal was always to keep it as simple as possible. 

I'm not familiar with async Python but I think you can always run the calls to `itunespy` in another thread if you need it, after all I assume that you just need it to be async to not block the UI when fetching data?
