### ISSUE TITLE
Release Dates

### ISSUE THREAD

**Issue by dualriposte** [sleepyfran/itunespy#6]
Can u add a feature which will show the release date of movies from different country stores

**Comment by sleepyfran** [comment]
Hi! You can already do this with the library. Every result has a field called `release_date` with which you can retrieve the release date of anything and the `search` method has a parameter called `country` with which you can modify the default one (US). So for example, if you wanted to retrieve the results from the United States, Spain and Portugal you can do this:

```python
import itunespy

us_results = itunespy.search('the incredibles') # Since USA is the default you can ignore the `country` parameter
es_results = itunespy.search('the incredibles', country='ES')
pt_results = itunespy.search('the incredibles', country='PT')
```

Since any of the `*_results` variables will be a list, you can retrieve the release date of the first result of each like this:

```python
us_release_date = us_results[0].release_date
es_release_date = es_results[0].release_date
pt_release_date = pt_results[0].release_date
```

And so on and so forth!
