### ISSUE TITLE
Documentation Clarification

### ISSUE THREAD

**Issue by jasonkolodziej** [sleepyfran/itunespy#8]
hi in your code file, it states a string to be passed...
but in your README.md you use an integer...

Could you please clarify which value type?
# --------
def lookup(id=None, artist_amg_id=None, upc=None, country='US', media='all', entity=None, attribute=None, limit=50):
    """
    Returns the result of the lookup of the specified id, artist_amg_id or upc in an array of result_item(s)
    :param id: String. iTunes ID of the artist, album, track, ebook or software
    :param artist_amg_id: String. All Music Guide ID of the artist
    :param upc: String. UPCs/EANs
    :param country: String. The two-letter country code for the store you want to search.
                    For a full list of the codes: http://en.wikipedia.org/wiki/%20ISO_3166-1_alpha-2
    :param media: String. The media type you want to search for. Example: music
    :param entity: String. The type of results you want returned, relative to the specified media type. Example: musicArtist.
                   Full list: musicArtist, musicTrack, album, musicVideo, mix, song
    :param attribute: String. The attribute you want to search for in the stores, relative to the specified media type.
    :param limit: Integer. The number of search results you want the iTunes Store to return.
    :return: An array of result_item(s)
    """

**Comment by sleepyfran** [comment]
Hi Jason!

The truth is it really doesn't matter because the value will be transformed to a string later on anyway, but this value is mostly always a number, or at least I can't find on the iTunes API documentation any mention of this lookup ID being anything other than a number. Most of the time this value should be retrieved from another search or lookup as a reference so you won't have to type it on your own.
